# These are supported funding model platforms

github: [Ichinya]
issuehunt: ichinya
custom: ['https://donate.stream/ichi', 'https://sobe.ru/na/yandex_turbo_for_mediawiki', 'https://paypal.me/ichinya']
